### ISSUE TITLE
[q] billing client 2.1.x support

### ISSUE THREAD

**Issue by vladp** [betterme-dev/RxBilling#18]
Wanted to upgrade my app to Android billing client 2.1.x
Is that possible, or should I wait for an updated release of rxBilling?

Asking because
according to this
https://developer.android.com/google/play/billing/billing_library_overview
there is a specific kotlin module that would need to be linked in
(our app is Java, does not use Kotlin, but I know that rxBilling uses it underneath)

> "If you're using Kotlin, the Play Billing Library KTX module contains Kotlin extensions and coroutines support that enable you to write idiomatic Kotlin in your Play Billing solution. To include these extensions in your project, add the following dependencies to your app's build.gradle file: "

**Comment by KChernenko** [comment]
Hi, sorry for the long response! You should wait for an update of the RxBilling. We'll do our best do roll out next release in a 2 weeks.

**Comment by tidimito** [comment]
KChernenko, when are you going to release  an update of the RxBilling?

**Comment by KChernenko** [comment]
@tidimito unfortunately, Google removed `IInAppBillingService` from the latest version of the billing client, so there are a bunch of changes needs to be done and we want to test the library's API internally before rollout.

**Comment by calmmycode** [comment]
Привіт. Вже вийшла версія 2.2

**Comment by KChernenko** [comment]
Hi! 
Thanks to the @dmytro-ostapovets we've released a new version of the library with billing client version `2.2.0` under the hood. 
Removing `IInAppBillingService` is postponed because probably all the library should be rewritten and unfortunately we don't have a spare time for this yet.

**Comment by vladp** [comment]
@KChernenko thank you for the support.
I looked at
https://developer.android.com/google/play/billing/billing_library_releases_notes
And they did not mention anything about AIDL removal, but they had mentioned it
https://developer.android.com/google/play/billing/api
without giving any dates/timeframes.

So it is not clear how long we can keep our apps using AIDL underneath.
I read that google started removing apps from their store, if was on 1.x billing API version.
So, I can only assume they will do same at some point with the 2.x users.
